version: 2
executorType: docker
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1
      - image: mysql:5.7.22
        environment:
          MYSQL_ROOT_PASSWORD: password
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ .Revision }}

      - run: 
          name: add lein voom
          command: mkdir ~/.lein && echo '{:user {:plugins [[lein-exec "0.3.5"] [lein-voom "0.1.0-20180617_140646-g0ba7ec8"]]}}' > ~/.lein/profiles.clj

      - run: 
          name: test
          command: ./test_projects.sh

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ .Branch }}-{{ .Revision }}
